name: 每日检测长江电力60日线

on:
  schedule:
    # 每天 9:40、10:30、13:30、14:50 自动运行
    - cron: '40 1 * * 1-5'
    - cron: '30 2 * * 1-5'
    - cron: '30 5 * * 1-5'
    - cron: '50 6 * * 1-5'
  workflow_dispatch:  # 支持手动运行

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行监控脚本
        env:
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          AUTH_CODE: ${{ secrets.AUTH_CODE }}
          RECEIVER: ${{ secrets.RECEIVER }}
        run: python main.py
